# shellcheck shell=bash
#
# noctoprevi - setup: doctor, benchmark latensi, integrasi idle daemon.

NC_HYPRIDLE_BEGIN="# >>> noctoprevi >>>"
NC_HYPRIDLE_END="# <<< noctoprevi <<<"

nc_detect_idle_daemon() {
    if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && nc_have hypridle; then
        printf 'hypridle'
    elif [ -n "${SWAYSOCK:-}" ] && nc_have swayidle; then
        printf 'swayidle'
    elif [ -n "${NIRI_SOCKET:-}" ] && nc_have swayidle; then
        printf 'swayidle'
    elif nc_have hypridle; then
        printf 'hypridle'
    elif nc_have swayidle; then
        printf 'swayidle'
    else
        printf ''
    fi
}

nc_idle_conf_path() {
    case "${1:-}" in
        hypridle) printf '%s/hypr/hypridle.conf' "${XDG_CONFIG_HOME:-$HOME/.config}" ;;
        swayidle) printf '%s/swayidle/config' "${XDG_CONFIG_HOME:-$HOME/.config}" ;;
        *) printf '' ;;
    esac
}

nc_hypridle_block() {
    cat <<EOF
$NC_HYPRIDLE_BEGIN
# Generated by $NC_APP $NC_VERSION - jangan diedit di dalam blok ini.
# Di-generate ulang dengan: $NC_APP install --idle-daemon hypridle

listener {
    timeout = $NC_IDLE_START_SEC
    on-timeout = $NC_APP start
}

listener {
    timeout = $NC_IDLE_LOCK_SEC
    on-timeout = noctalia msg lock
}

listener {
    timeout = 0
    on-resume = $NC_APP stop
}
$NC_HYPRIDLE_END
EOF
}

nc_swayidle_block() {
    cat <<EOF
$NC_HYPRIDLE_BEGIN
# Generated by $NC_APP $NC_VERSION - jangan diedit di dalam blok ini.
# Di-generate ulang dengan: $NC_APP install --idle-daemon swayidle

# Screensaver menyala setelah idle, lock setelah idle lebih lama.
exec_while_idle = $NC_APP start
# Prompt lock milik Noctalia, menyala sendiri setelah $NC_IDLE_LOCK_SEC detik.
exec_on_idle = sleep $NC_IDLE_LOCK_SEC; $NC_APP stop; noctalia msg lock
# Input pengguna: matikan screensaver secepat mungkin.
exec_idle_deadline = 0
# Dipanggil saat resume - ini yang menjaga latensi tetap rendah.
exec_on_resume = $NC_APP stop
$NC_HYPRIDLE_END
EOF
}

nc_block_for() {
    case "$1" in
        hypridle) nc_hypridle_block ;;
        swayidle) nc_swayidle_block ;;
        *) return 1 ;;
    esac
}

nc_strip_block() {
    local file="$1"
    [ -f "$file" ] || return 0
    local tmp="$file.nctmp.$$"
    awk -v b="$NC_HYPRIDLE_BEGIN" -v e="$NC_HYPRIDLE_END" '
        $0 == b { skip = 1; next }
        $0 == e { skip = 0; next }
        skip   { next }
        {
            if ($0 ~ /^[[:space:]]*$/ && prev_blank) next
            print
            prev_blank = ($0 ~ /^[[:space:]]*$/)
        }
    ' "$file" >"$tmp" 2>/dev/null || {
        rm -f "$tmp" 2>/dev/null
        return 1
    }
    mv -f "$tmp" "$file" 2>/dev/null
}

nc_install_idle() {
    local daemon="$1"
    local conf
    conf="$(nc_idle_conf_path "$daemon")"
    if [ -z "$conf" ]; then
        nc_log_error "daemon tidak dikenal: $daemon"
        return "$NC_EXIT_USAGE"
    fi

    local dir="${conf%/*}"
    mkdir -p "$dir" 2>/dev/null || {
        nc_log_error "gagal membuat $dir"
        return "$NC_EXIT_ERROR"
    }

    if [ -f "$conf" ]; then
        cp -f "$conf" "$conf.nocbackup" 2>/dev/null &&
            nc_log_info "backup: $conf.nocbackup"
        nc_strip_block "$conf" || nc_log_warn "gagal membersihkan blok lama"
    fi

    {
        printf '\n\n'
        nc_block_for "$daemon"
        printf '\n'
    } >>"$conf" 2>/dev/null || {
        nc_log_error "gagal menulis $conf"
        return "$NC_EXIT_ERROR"
    }

    nc_log_info "terpasang: $conf"
    printf '\n'
    printf 'Muat ulang daemon:\n'
    case "$daemon" in
        hypridle) printf '  hyprctl reload\n' ;;
        swayidle) printf '  swaymsg reload\n' ;;
    esac
    printf 'Uji manual: %s toggle\n' "$NC_APP"
    return "$NC_EXIT_OK"
}

nc_uninstall_idle() {
    local daemon="$1"
    local conf
    conf="$(nc_idle_conf_path "$daemon")"
    [ -n "$conf" ] || return "$NC_EXIT_USAGE"
    if [ ! -f "$conf" ]; then
        nc_log_info "tidak ada: $conf"
        return "$NC_EXIT_OK"
    fi
    nc_strip_block "$conf" || {
        nc_log_error "gagal membersihkan $conf"
        return "$NC_EXIT_ERROR"
    }
    nc_log_info "blok noctoprevi dibuang dari $conf"
    return "$NC_EXIT_OK"
}

nc_cmd_install() {
    local daemon="" do_config=1
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --idle-daemon)
                daemon="${2:-}"
                shift 2
                ;;
            --no-config) do_config=0; shift ;;
            --daemon) daemon="${2:-}"; shift 2 ;;
            -h | --help)
                printf 'Pakai: %s install [--idle-daemon hypridle|swayidle] [--no-config]\n' "$NC_APP"
                return "$NC_EXIT_OK"
                ;;
            *) shift ;;
        esac
    done

    [ "$do_config" -eq 1 ] && nc_setup_config_dirs

    if [ -z "$daemon" ]; then
        daemon="$(nc_detect_idle_daemon)"
    fi
    if [ -z "$daemon" ]; then
        nc_log_warn "daemon idle tidak terdeteksi (hypridle/swayidle)"
        printf 'Sebutkan manual, contoh:\n  %s install --idle-daemon swayidle\n' "$NC_APP"
        return "$NC_EXIT_OK"
    fi
    nc_install_idle "$daemon"
}

nc_cmd_uninstall() {
    local daemon=""
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --idle-daemon | --daemon) daemon="${2:-}"; shift 2 ;;
            *) shift ;;
        esac
    done
    [ -n "$daemon" ] || daemon="$(nc_detect_idle_daemon)"

    local rc=0
    if [ -n "$daemon" ]; then
        nc_uninstall_idle "$daemon" || rc=$?
    else
        nc_uninstall_idle hypridle || rc=$?
        nc_uninstall_idle swayidle || rc=$?
    fi

    nc_cmd_stop >/dev/null 2>&1
    nc_log_info "selesai. Lock file & socket runtime dibersihkan saat stop."
    return "$rc"
}

nc_setup_config_dirs() {
    mkdir -p "$NC_CONFIG_DIR" "$NC_VIDEO_DIR" 2>/dev/null
    if [ ! -f "$NC_CONFIG_FILE" ]; then
        if nc_config_write_default "$NC_CONFIG_FILE"; then
            nc_log_info "config dibuat: $NC_CONFIG_FILE"
        fi
    else
        nc_log_info "config sudah ada: $NC_CONFIG_FILE"
    fi
    if [ ! -d "$NC_VIDEO_DIR" ]; then
        nc_log_info "direktori video: $NC_VIDEO_DIR"
    fi
    return 0
}

nc_doctor_ok() { printf '  \033[32mOK\033[0m    %s\n' "$*"; }
nc_doctor_warn() { printf '  \033[33mWARN\033[0m  %s\n' "$*"; }
nc_doctor_err() { printf '  \033[31mFAIL\033[0m  %s\n' "$*"; }
nc_doctor_info() { printf '  INFO  %s\n' "$*"; }

nc_check_dep() {
    local bin="$1" hint="${2:-}"
    local path
    path="$(nc_which "$bin")"
    if [ -n "$path" ]; then
        nc_doctor_ok "$bin -> $path"
        return 0
    fi
    if [ -n "$hint" ]; then
        nc_doctor_err "$bin tidak ditemukan ($hint)"
    else
        nc_doctor_err "$bin tidak ditemukan"
    fi
    return 1
}

nc_check_hardware_decode() {
    local -a lines
    local line ok=0
    if [ ! -d /dev/dri ]; then
        nc_doctor_warn "/dev/dri tidak ada, akselerasi GPU tidak tersedia"
        return 1
    fi
    if ! nc_have vainfo; then
        nc_doctor_info "vainfo tidak ada, lewati deteksi VA-API"
    else
        while IFS= read -r line; do
            case "$line" in
                *vainfo*|*Driver*|*Profile*)
                    nc_doctor_info "$line"
                    ;;
            esac
        done < <(vainfo 2>/dev/null | head -20)
    fi
    if [ -e /dev/dri/renderD128 ] || [ -e /dev/dri/card0 ]; then
        nc_doctor_ok "node DRM tersedia di /dev/dri"
        ok=1
    fi
    if [ "$NC_HWDEC" = "auto" ] && [ "$ok" -eq 0 ]; then
        nc_doctor_warn "hwdec=auto tanpa node DRM, mpv akan jatuh ke decoding lunak"
    fi
    return 0
}

nc_cmd_doctor() {
    local rc=0

    printf '%s %s\n' "$NC_APP" "$NC_VERSION"
    printf '%s\n' "------------------------------------------------------------------"

    printf 'Lingkungan\n'
    printf '  %-16s %s\n' "session" "${XDG_SESSION_TYPE:-tidak diketahui}"
    printf '  %-16s %s\n' "compositor" "$(
        if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then printf 'Hyprland'
        elif [ -n "${NIRI_SOCKET:-}" ]; then printf 'Niri'
        elif [ -n "${SWAYSOCK:-}" ]; then printf 'Sway'
        else printf 'tidak diketahui'; fi
    )"
    printf '  %-16s %s\n' "XDG_RUNTIME_DIR" "$NC_RUNTIME_DIR"
    printf '  %-16s %s\n' "XDG_CONFIG_HOME" "${XDG_CONFIG_HOME:-$HOME/.config}"
    printf '  %-16s %s\n' "shell" "$NC_APP"

    printf '\nDependensi\n'
    nc_check_dep mpv "pacman -S mpv" || rc=1
    nc_check_dep socat "pacman -S socat" || rc=1
    nc_check_dep flock "util-linux" || rc=1
    nc_check_dep ffmpeg "opsional, untuk aerials" ||
        nc_doctor_info "ffmpeg tidak ada, unduh aerials tidak bisa diproses"
    nc_check_dep ffprobe "opsional, untuk validasi media" ||
        nc_doctor_info "ffprobe tidak ada, validasi dilewati"
    nc_check_dep jq "opsional, untuk output multi-monitor" ||
        nc_doctor_info "jq tidak ada, output monitor tidak dideteksi"

    printf '\nIdle daemon\n'
    local daemon
    daemon="$(nc_detect_idle_daemon)"
    if [ -n "$daemon" ]; then
        nc_doctor_ok "terdeteksi: $daemon"
        local conf
        conf="$(nc_idle_conf_path "$daemon")"
        if [ -f "$conf" ] && grep -qF "$NC_HYPRIDLE_BEGIN" "$conf" 2>/dev/null; then
            nc_doctor_ok "blok noctoprevi terpasang di $conf"
        else
            nc_doctor_warn "belum terpasang, jalankan: $NC_APP install --idle-daemon $daemon"
        fi
    else
        nc_doctor_warn "hypridle/swayidle tidak ditemukan"
    fi

    printf '\nLockscreen\n'
    if nc_have noctalia-shell-shellctl || nc_have noctalia; then
        nc_doctor_ok "noctalia tersedia"
        if nc_have noctalia-shell-shellctl; then
            printf '        FORMAT="noctalia msg lock" | %s exec bash -lc >&2\n' \
                "$(nc_which noctalia-shell-shellctl)"
        fi
    else
        nc_doctor_warn "noctalia tidak ditemukan, lockscreen won't dipicu otomatis"
    fi

    printf '\nKonfigurasi\n'
    if [ -f "$NC_CONFIG_FILE" ]; then
        nc_doctor_ok "$NC_CONFIG_FILE"
    else
        nc_doctor_warn "belum ada: $NC_CONFIG_FILE (jalankan: $NC_APP install)"
    fi
    printf '  %-16s %s\n' "VIDEO_DIR" "$NC_VIDEO_DIR"
    printf '  %-16s %s\n' "PLAYBACK_MODE" "$NC_PLAYBACK_MODE"
    printf '  %-16s %s\n' "HWDEC" "$NC_HWDEC"
    printf '  %-16s %s\n' "AUDIO" "$NC_AUDIO"
    printf '  %-16s %s\n' "MONITOR_MODE" "$NC_MONITOR_MODE"
    printf '  %-16s %s\n' "CURSOR_AUTOHIDE" "$NC_CURSOR_AUTOHIDE"
    printf '  %-16s %s\n' "RETRY_LIMIT" "$NC_RETRY_LIMIT"
    printf '  %-16s %s\n' "LOG" "$NC_LOG_TARGET${NC_LOG_FILE:+ -> $NC_LOG_FILE}"
    if [ -n "$NC_CFG_UNKNOWN" ]; then
        nc_doctor_warn "key config tidak dikenal: $NC_CFG_UNKNOWN"
    fi

    printf '\nMedia\n'
    if [ -d "$NC_VIDEO_DIR" ]; then
        local -i count=0
        local f
        for f in "$NC_VIDEO_DIR"/*; do
            [ -f "$f" ] && count=$(( count + 1 ))
        done
        if [ "$count" -gt 0 ]; then
            nc_doctor_ok "$count file di $NC_VIDEO_DIR"
        else
            nc_doctor_warn "direktori video kosong: $NC_VIDEO_DIR"
            printf '        Jalankan: %s aerials --sync\n' "$NC_APP"
        fi
    else
        nc_doctor_err "direktori video tidak ada: $NC_VIDEO_DIR"
    fi

    printf '\nOutput monitor\n'
    if nc_detect_outputs; then
        for f in "${NC_OUTPUTS[@]}"; do
            nc_doctor_ok "$f"
        done
    else
        nc_doctor_warn "tidak bisa mendeteksi output monitor"
    fi

    printf '\nAkselerasi\n'
    nc_check_hardware_decode

    printf '\nRuntime\n'
    printf '  %-16s %s\n' "socket" "$NC_SOCK"
    if [ -n "$NC_RUNTIME_INFIX" ]; then
        printf '  %-16s %s\n' "catatan" "XDG_RUNTIME_DIR tak bisa dipakai, suffix per-UID aktif"
    fi
    if nc_is_running; then
        nc_doctor_ok "aktif (supervisor pid $(nc_supervisor_pid 2>/dev/null))"
    else
        nc_doctor_info "tidak aktif"
    fi
    if [ -S "$NC_SOCK" ]; then
        nc_doctor_ok "socket live: $NC_SOCK"
    else
        nc_doctor_info "socket tidak ada (normal saat tidak aktif)"
    fi
    if nc_lock_probe_free; then
        nc_doctor_ok "lock bebas (tidak ada instance lain)"
    else
        nc_doctor_warn "lock dipegang instance lain"
    fi

    printf '%s\n' "------------------------------------------------------------------"
    if [ "$rc" -eq 0 ]; then
        printf 'Kesimpulan: siap dipakai.\n'
    else
        printf 'Kesimpulan: ada dependensi wajib yang belum terpasang.\n'
    fi
    return "$rc"
}

nc_cmd_bench() {
    local -i runs=10
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --runs | -n)
                case "${2:-}" in
                    '' | *[!0-9]*) runs=10 ;;
                    *) runs="$2" ;;
                esac
                shift
                ;;
            [0-9]*) runs="$1" ;;
        esac
        shift
    done
    [ "$runs" -ge 1 ] && [ "$runs" -le 200 ] || runs=10

    local media_count
    media_count="$(nc_media_count_quick)"
    if [ "$media_count" -eq 0 ]; then
        nc_log_error "tidak ada media di $NC_VIDEO_DIR, bench dibatalkan"
        return "$NC_EXIT_ERROR"
    fi

    printf 'Benchmark %s: %d putaran (start -> stop)\n' "$NC_APP" "$runs"
    printf '%-6s %-12s %-12s %-12s\n' "run" "start(ms)" "stop(ms)" "total(ms)"

    local -i i
    local -a stops=()
    local -i t0 t1 t2 start_ms stop_ms total_ms sum=0
    local -a totals=()

    for (( i = 1; i <= runs; i++ )); do
        t0="$(nc_now_us)"
        nc_cmd_start >/dev/null 2>&1
        t1="$(nc_now_us)"
        nc_cmd_stop >/dev/null 2>&1
        t2="$(nc_now_us)"

        start_ms="$(nc_us_to_ms "$(( t1 - t0 ))")"
        stop_ms="$(nc_us_to_ms "$(( t2 - t1 ))")"
        total_ms="$(nc_us_to_ms "$(( t2 - t0 ))")"
        stops+=("$stop_ms")
        totals+=("$total_ms")
        sum=$(( sum + stop_ms ))
        printf '%-6s %-12s %-12s %-12s\n' "$i" "$start_ms" "$stop_ms" "$total_ms"
    done

    printf '\n'
    nc_bench_stats "stop" "${stops[@]}" "$NC_STOP_IPC_WAIT_MS"
    nc_bench_stats "total" "${totals[@]}" ""
    return "$NC_EXIT_OK"
}

nc_bench_stats() {
    local label="$1" budget="$2"
    shift 2
    local -a v=("$@")
    local -i n="${#v[@]}" i j tmp
    for (( i = 1; i < n; i++ )); do
        tmp="${v[i]}"
        j=$(( i - 1 ))
        while [ "$j" -ge 0 ] && [ "${v[j]}" -gt "$tmp" ]; do
            v[$(( j + 1 ))]="${v[j]}"
            j=$(( j - 1 ))
        done
        v[$(( j + 1 ))]="$tmp"
    done
    local -i sum=0 min max avg p50 p95
    for i in "${v[@]}"; do sum=$(( sum + i )); done
    min="${v[0]}"
    max="${v[n - 1]}"
    avg=$(( sum / n ))
    p50="${v[$(( n / 2 ))]}"
    p95="${v[$(( (n * 95) / 100 >= n ? n - 1 : (n * 95) / 100 ))]}"
    printf '%-6s min=%sms  p50=%sms  p95=%sms  max=%sms  rata-rata=%sms' \
        "$label" "$min" "$p50" "$p95" "$max" "$avg"
    if [ -n "$budget" ]; then
        if [ "$p95" -le "$budget" ]; then
            printf '  [OK, di bawah anggaran %sms]' "$budget"
        else
            printf '  [LEBIH dari anggaran %sms]' "$budget"
        fi
    fi
    printf '\n'
}

nc_media_count_quick() {
    local -i n=0
    local f
    for f in "$NC_VIDEO_DIR"/*; do
        [ -f "$f" ] && n=$(( n + 1 ))
    done
    printf '%s' "$n"
}
