# shellcheck shell=bash
#
# noctoprevi - setup: doctor, benchmark latensi, integrasi idle daemon.

NC_HYPRIDLE_BEGIN="# >>> noctoprevi >>>"
NC_HYPRIDLE_END="# <<< noctoprevi <<<"

nc_detect_idle_daemon() {
    if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && nc_have hypridle; then
        printf 'hypridle'
    elif [ -n "${SWAYSOCK:-}" ] && nc_have swayidle; then
        printf 'swayidle'
    elif [ -n "${NIRI_SOCKET:-}" ] && nc_have swayidle; then
        printf 'swayidle'
    elif nc_have hypridle; then
        printf 'hypridle'
    elif nc_have swayidle; then
        printf 'swayidle'
    else
        printf ''
    fi
}

nc_idle_conf_path() {
    case "${1:-}" in
        hypridle) printf '%s/hypr/hypridle.conf' "${XDG_CONFIG_HOME:-$HOME/.config}" ;;
        swayidle) printf '%s/swayidle/config' "${XDG_CONFIG_HOME:-$HOME/.config}" ;;
        *) printf '' ;;
    esac
}

nc_hypridle_block() {
    cat <<EOF
$NC_HYPRIDLE_BEGIN
# Generated by $NC_APP $NC_VERSION - jangan diedit di dalam blok ini.
# Di-generate ulang dengan: $NC_APP install --idle-daemon hypridle

listener {
    timeout = $NC_IDLE_START_SEC
    on-timeout = $NC_APP start
}

listener {
    timeout = $NC_IDLE_LOCK_SEC
    on-timeout = noctalia msg lock
}

listener {
    timeout = 0
    on-resume = $NC_APP stop
}
$NC_HYPRIDLE_END
EOF
}

nc_swayidle_block() {
    cat <<EOF
$NC_HYPRIDLE_BEGIN
# Generated by $NC_APP $NC_VERSION - jangan diedit di dalam blok ini.
# Di-generate ulang dengan: $NC_APP install --idle-daemon swayidle

# Screensaver menyala setelah idle, lock setelah idle lebih lama.
exec_while_idle = $NC_APP start
# Prompt lock milik Noctalia, menyala sendiri setelah $NC_IDLE_LOCK_SEC detik.
exec_on_idle = sleep $NC_IDLE_LOCK_SEC; $NC_APP stop; noctalia msg lock
# Input pengguna: matikan screensaver secepat mungkin.
exec_idle_deadline = 0
# Dipanggil saat resume - ini yang menjaga latensi tetap rendah.
exec_on_resume = $NC_APP stop
$NC_HYPRIDLE_END
EOF
}

nc_block_for() {
    case "$1" in
        hypridle) nc_hypridle_block ;;
        swayidle) nc_swayidle_block ;;
        *) return 1 ;;
    esac
}

nc_strip_block() {
    local file="$1"
    [ -f "$file" ] || return 0
    local tmp="$file.nctmp.$$"
    awk -v b="$NC_HYPRIDLE_BEGIN" -v e="$NC_HYPRIDLE_END" '
        $0 == b { skip = 1; next }
        $0 == e { skip = 0; next }
        skip   { next }
        {
            if ($0 ~ /^[[:space:]]*$/ && prev_blank) next
            print
            prev_blank = ($0 ~ /^[[:space:]]*$/)
        }
    ' "$file" >"$tmp" 2>/dev/null || {
        rm -f "$tmp" 2>/dev/null
        return 1
    }
    mv -f "$tmp" "$file" 2>/dev/null
}

nc_install_idle() {
    local daemon="$1"
    local conf
    conf="$(nc_idle_conf_path "$daemon")"
    if [ -z "$conf" ]; then
        nc_log_error "daemon tidak dikenal: $daemon"
        return "$NC_EXIT_USAGE"
    fi

    local dir="${conf%/*}"
    mkdir -p "$dir" 2>/dev/null || {
        nc_log_error "gagal membuat $dir"
        return "$NC_EXIT_ERROR"
    }

    if [ -f "$conf" ]; then
        cp -f "$conf" "$conf.nocbackup" 2>/dev/null &&
            nc_log_info "backup: $conf.nocbackup"
        nc_strip_block "$conf" || nc_log_warn "gagal membersihkan blok lama"
    fi

    {
        printf '\n\n'
        nc_block_for "$daemon"
        printf '\n'
    } >>"$conf" 2>/dev/null || {
        nc_log_error "gagal menulis $conf"
        return "$NC_EXIT_ERROR"
    }

    nc_log_info "terpasang: $conf"
    printf '\n'
    printf 'Muat ulang daemon:\n'
    case "$daemon" in
        hypridle) printf '  hyprctl reload\n' ;;
        swayidle) printf '  swaymsg reload\n' ;;
    esac
    printf 'Uji manual: %s toggle\n' "$NC_APP"
    return "$NC_EXIT_OK"
}

nc_uninstall_idle() {
    local daemon="$1"
    local conf
    conf="$(nc_idle_conf_path "$daemon")"
    [ -n "$conf" ] || return "$NC_EXIT_USAGE"
    if [ ! -f "$conf" ]; then
        nc_log_info "tidak ada: $conf"
        return "$NC_EXIT_OK"
    fi
    nc_strip_block "$conf" || {
        nc_log_error "gagal membersihkan $conf"
        return "$NC_EXIT_ERROR"
    }
    nc_log_info "blok noctoprevi dibuang dari $conf"
    return "$NC_EXIT_OK"
}

nc_cmd_install() {
    local daemon="" do_config=1
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --idle-daemon)
                daemon="${2:-}"
                shift 2
                ;;
            --no-config) do_config=0; shift ;;
            --daemon) daemon="${2:-}"; shift 2 ;;
            -h | --help)
                printf 'Pakai: %s install [--idle-daemon hypridle|swayidle] [--no-config]\n' "$NC_APP"
                return "$NC_EXIT_OK"
                ;;
            *) shift ;;
        esac
    done

    [ "$do_config" -eq 1 ] && nc_setup_config_dirs

    if [ -z "$daemon" ]; then
        daemon="$(nc_detect_idle_daemon)"
    fi
    if [ -z "$daemon" ]; then
        nc_log_warn "daemon idle tidak terdeteksi (hypridle/swayidle)"
        printf 'Sebutkan manual, contoh:\n  %s install --idle-daemon swayidle\n' "$NC_APP"
        return "$NC_EXIT_OK"
    fi
    nc_install_idle "$daemon"
}

nc_cmd_uninstall() {
    local daemon=""
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --idle-daemon | --daemon) daemon="${2:-}"; shift 2 ;;
            *) shift ;;
        esac
    done
    [ -n "$daemon" ] || daemon="$(nc_detect_idle_daemon)"

    local rc=0
    if [ -n "$daemon" ]; then
        nc_uninstall_idle "$daemon" || rc=$?
    else
        nc_uninstall_idle hypridle || rc=$?
        nc_uninstall_idle swayidle || rc=$?
    fi

    nc_cmd_stop >/dev/null 2>&1
    nc_log_info "selesai. Lock file & socket runtime dibersihkan saat stop."
    return "$rc"
}

nc_setup_config_dirs() {
    mkdir -p "$NC_CONFIG_DIR" "$NC_VIDEO_DIR" 2>/dev/null
    if [ ! -f "$NC_CONFIG_FILE" ]; then
        if nc_config_write_default "$NC_CONFIG_FILE"; then
            nc_log_info "config dibuat: $NC_CONFIG_FILE"
        fi
    else
        nc_log_info "config sudah ada: $NC_CONFIG_FILE"
    fi
    if [ ! -d "$NC_VIDEO_DIR" ]; then
        nc_log_info "direktori video: $NC_VIDEO_DIR"
    fi
    return 0
}

nc_doctor_ok() { printf '  \033[32mOK\033[0m    %s\n' "$*"; }
nc_doctor_warn() { printf '  \033[33mWARN\033[0m  %s\n' "$*"; }
nc_doctor_err() { printf '  \033[31mFAIL\033[0m  %s\n' "$*"; }
nc_doctor_info() { printf '  INFO  %s\n' "$*"; }

nc_check_dep() {
    local bin="$1" hint="${2:-}"
    local path
    path="$(nc_which "$bin")"
    if [ -n "$path" ]; then
        nc_doctor_ok "$bin -> $path"
        return 0
    fi
    if [ -n "$hint" ]; then
        nc_doctor_err "$bin tidak ditemukan ($hint)"
    else
        nc_doctor_err "$bin tidak ditemukan"
    fi
    return 1
}

nc_check_hardware_decode() {
    local -a lines
    local line ok=0
    if [ ! -d /dev/dri ]; then
        nc_doctor_warn "/dev/dri tidak ada, akselerasi GPU tidak tersedia"
        return 1
    fi
    if ! nc_have vainfo; then
        nc_doctor_info "vainfo tidak ada, lewati deteksi VA-API"
    else
        while IFS= read -r line; do
            case "$line" in
                *vainfo*|*Driver*|*Profile*)
                    nc_doctor_info "$line"
                    ;;
            esac
        done < <(vainfo 2>/dev/null | head -20)
    fi
    if [ -e /dev/dri/renderD128 ] || [ -e /dev/dri/card0 ]; then
        nc_doctor_ok "node DRM tersedia di /dev/dri"
        ok=1
    fi
    if [ "$NC_HWDEC" = "auto" ] && [ "$ok" -eq 0 ]; then
        nc_doctor_warn "hwdec=auto tanpa node DRM, mpv akan jatuh ke decoding lunak"
    fi
    return 0
}

nc_cmd_doctor() {
    local rc=0

    printf '%s %s\n' "$NC_APP" "$NC_VERSION"
    printf '%s\n' "------------------------------------------------------------------"

    printf 'Lingkungan\n'
    printf '  %-16s %s\n' "session" "${XDG_SESSION_TYPE:-tidak diketahui}"
    printf '  %-16s %s\n' "compositor" "$(
        if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then printf 'Hyprland'
        elif [ -n "${NIRI_SOCKET:-}" ]; then printf 'Niri'
        elif [ -n "${SWAYSOCK:-}" ]; then printf 'Sway'
        else printf 'tidak diketahui'; fi
    )"
    printf '  %-16s %s\n' "XDG_RUNTIME_DIR" "$NC_RUNTIME_DIR"
    printf '  %-16s %s\n' "XDG_CONFIG_HOME" "${XDG_CONFIG_HOME:-$HOME/.config}"
    printf '  %-16s %s\n' "shell" "$NC_APP"

    printf '\nDependensi\n'
    nc_check_dep mpv "pacman -S mpv" || rc=1
    nc_check_dep socat "pacman -S socat" || rc=1
    nc_check_dep flock "util-linux" || rc=1
    nc_check_dep ffmpeg "opsional, untuk aerials" ||
        nc_doctor_info "ffmpeg tidak ada, unduh aerials tidak bisa diproses"
    nc_check_dep ffprobe "opsional, untuk validasi media" ||
        nc_doctor_info "ffprobe tidak ada, validasi dilewati"
    nc_check_dep jq "opsional, untuk output multi-monitor" ||
        nc_doctor_info "jq tidak ada, output monitor tidak dideteksi"

    printf '\nIdle\n'
    printf '  %-16s %ss\n' "screensaver" "$NC_IDLE_START_SEC"
    printf '  %-16s %ss\n' "lockscreen" "$NC_IDLE_LOCK_SEC"

    local daemon conf
    daemon="$(nc_detect_idle_daemon)"
    if [ -n "$daemon" ]; then
        printf '  %-16s %s\n' "daemon" "$daemon"
    else
        printf '  %-16s %s\n' "daemon" "tidak ditemukan"
        nc_doctor_warn "hypridle atau swayidle belum terpasang"
        printf '        sudo pacman -S swayidle\n'
    fi

    conf="$(nc_idle_conf_path "${daemon:-swayidle}")"
    if [ -f "$conf" ] && grep -qF "$NC_HYPRIDLE_BEGIN" "$conf" 2>/dev/null; then
        nc_doctor_ok "blok noctoprevi terpasang di $conf"
    else
        printf '  %-16s %s\n' "blok idle" "belum terpasang"
        printf '        %s install --idle-daemon %s\n' "$NC_APP" "${daemon:-swayidle}"
    fi

    printf '\nLockscreen\n'
    if nc_have noctalia-shell-shellctl || nc_have noctalia; then
        nc_doctor_ok "noctalia tersedia"
        if nc_have noctalia-shell-shellctl; then
            printf '        FORMAT="noctalia msg lock" | %s exec bash -lc >&2\n' \
                "$(nc_which noctalia-shell-shellctl)"
        fi
    else
        nc_doctor_warn "noctalia tidak ditemukan, lockscreen won't dipicu otomatis"
    fi

    printf '\nKonfigurasi\n'
    if [ -f "$NC_CONFIG_FILE" ]; then
        nc_doctor_ok "$NC_CONFIG_FILE"
    else
        nc_doctor_warn "belum ada: $NC_CONFIG_FILE (jalankan: $NC_APP install)"
    fi
    printf '  %-16s %s\n' "VIDEO_DIR" "$NC_VIDEO_DIR"
    printf '  %-16s %s\n' "PLAYBACK_MODE" "$NC_PLAYBACK_MODE"
    printf '  %-16s %s\n' "HWDEC" "$NC_HWDEC"
    printf '  %-16s %s\n' "AUDIO" "$NC_AUDIO"
    printf '  %-16s %s\n' "MONITOR_MODE" "$NC_MONITOR_MODE"
    printf '  %-16s %s\n' "CURSOR_AUTOHIDE" "$NC_CURSOR_AUTOHIDE"
    printf '  %-16s %s\n' "VIDEO_FPS_LIMIT" "$(
        [ "${NC_VIDEO_FPS_LIMIT:-0}" -gt 0 ] 2>/dev/null &&
            printf '%s fps' "$NC_VIDEO_FPS_LIMIT" || printf 'mati (semua frame)'
    )"
    printf '  %-16s %s\n' "RETRY_LIMIT" "$NC_RETRY_LIMIT"
    printf '  %-16s %s (%ss min)\n' "VALIDATE_MEDIA" "$NC_VALIDATE_MEDIA" "$NC_MIN_DURATION_SEC"
    printf '  %-16s %s\n' "AERIALS_TRUST" "$NC_AERIALS_TRUST"
    printf '  %-16s %s\n' "LOG" "$NC_LOG_TARGET${NC_LOG_FILE:+ -> $NC_LOG_FILE}"
    if [ -n "$NC_CFG_UNKNOWN" ]; then
        nc_doctor_warn "key config tidak dikenal: $NC_CFG_UNKNOWN"
    fi

    printf '\nMedia\n'
    if [ -d "$NC_VIDEO_DIR" ]; then
        local -i count=0
        local f
        for f in "$NC_VIDEO_DIR"/*; do
            [ -f "$f" ] && count=$(( count + 1 ))
        done
        if [ "$count" -gt 0 ]; then
            nc_doctor_ok "$count file di $NC_VIDEO_DIR"
        else
            nc_doctor_warn "direktori video kosong: $NC_VIDEO_DIR"
            printf '        Jalankan: %s aerials --sync\n' "$NC_APP"
        fi
    else
        nc_doctor_err "direktori video tidak ada: $NC_VIDEO_DIR"
    fi

    printf '\nOutput monitor\n'
    if nc_detect_outputs; then
        for f in "${NC_OUTPUTS[@]}"; do
            nc_doctor_ok "$f"
        done
    else
        nc_doctor_warn "tidak bisa mendeteksi output monitor"
    fi

    printf '\nAkselerasi\n'
    nc_check_hardware_decode

    printf '\nRuntime\n'
    printf '  %-16s %s\n' "socket" "$NC_SOCK"
    if [ -n "$NC_RUNTIME_INFIX" ]; then
        printf '  %-16s %s\n' "catatan" "XDG_RUNTIME_DIR tak bisa dipakai, suffix per-UID aktif"
    fi
    if nc_is_running; then
        nc_doctor_ok "aktif (supervisor pid $(nc_supervisor_pid 2>/dev/null))"
    else
        nc_doctor_info "tidak aktif"
    fi
    if [ -S "$NC_SOCK" ]; then
        nc_doctor_ok "socket live: $NC_SOCK"
    else
        nc_doctor_info "socket tidak ada (normal saat tidak aktif)"
    fi
    if nc_lock_probe_free; then
        nc_doctor_ok "lock bebas (tidak ada instance lain)"
    else
        nc_doctor_warn "lock dipegang instance lain"
    fi

    printf '%s\n' "------------------------------------------------------------------"
    if [ "$rc" -eq 0 ]; then
        printf 'Kesimpulan: siap dipakai.\n'
    else
        printf 'Kesimpulan: ada dependensi wajib yang belum terpasang.\n'
    fi
    return "$rc"
}

nc_bench_escalation_sweep() {
    local -i runs="${1:-6}"
    local -a points=(0 5 10 20 50 100)
    local -a samples=()
    local -i p i t0 t1 ms sum live=0
    local orig="$NC_STOP_IPC_WAIT_MS"

    local media
    media="$(nc_media_count_quick)"
    if [ "$media" -eq 0 ]; then
        nc_log_error "tidak ada media di $NC_VIDEO_DIR, sweep dibatalkan"
        return "$NC_EXIT_ERROR"
    fi

    printf 'Escalation sweep: %d putaran per titik, total %d siklus.\n' \
        "$runs" "$(( runs * ${#points[@]} ))"
    printf 'STOP_IPC_WAIT_MS mengukur berapa lama menunggu IPC quit\n'
    printf 'sebelum naik ke SIGTERM. 0 = langsung SIGTERM.\n\n'
    printf '%-20s %-10s %-10s %-10s\n' "STOP_IPC_WAIT_MS" "p50(ms)" "p95(ms)" "maks(ms)"

    for p in "${points[@]}"; do
        NC_STOP_IPC_WAIT_MS="$p"
        samples=()
        for (( i = 1; i <= runs; i++ )); do
            nc_cmd_start >/dev/null 2>&1
            nc_pid_alive "$(nc_supervisor_pid 2>/dev/null)" && live=$(( live + 1 ))
            sleep 0.3
            t0="$(nc_now_us)"
            nc_cmd_stop >/dev/null 2>&1
            t1="$(nc_now_us)"
            ms=$(( (t1 - t0) / 1000 ))
            samples+=("$ms")
        done
        printf '  %-16s mentah: %-28s (supervisor hidup %s/%s)\n' \
            "$p" "${samples[*]}" "$live" "$runs"
        nc_bench_stats "$p" "" "${samples[@]}"
        live=0
    done

    NC_STOP_IPC_WAIT_MS="$orig"
    printf '\n'
    printf 'Angka di atas adalah waktu total perintah `stop` dari luar, jadi\n'
    printf 'sudah termasuk start-up CLI. Bandingkan antar titik, bukan\n'
    printf 'dengan angka di dokumentasi - itu dari mesin lain.\n'
    return "$NC_EXIT_OK"
}

nc_cmd_bench() {
    local -i runs=10
    local sweep=0
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --runs | -n)
                case "${2:-}" in
                    '' | *[!0-9]*) runs=10 ;;
                    *) runs="$2" ;;
                esac
                shift
                ;;
            --escalation-sweep | --sweep) sweep=1; shift ;;
            [0-9]*) runs="$1" ;;
        esac
        shift
    done
    [ "$runs" -ge 1 ] && [ "$runs" -le 200 ] || runs=10

    if [ "$sweep" -eq 1 ]; then
        nc_bench_escalation_sweep "$runs"
        return $?
    fi

    local media_count
    media_count="$(nc_media_count_quick)"
    if [ "$media_count" -eq 0 ]; then
        nc_log_error "tidak ada media di $NC_VIDEO_DIR, bench dibatalkan"
        return "$NC_EXIT_ERROR"
    fi

    printf 'Benchmark %s: %d putaran (start -> stop)\n' "$NC_APP" "$runs"
    printf '%-6s %-12s %-12s %-12s\n' "run" "start(ms)" "stop(ms)" "total(ms)"

    local -i i
    local -a stops=()
    local -i t0 t1 t2 start_ms stop_ms total_ms sum=0
    local -a totals=()

    for (( i = 1; i <= runs; i++ )); do
        t0="$(nc_now_us)"
        nc_cmd_start >/dev/null 2>&1
        t1="$(nc_now_us)"
        nc_cmd_stop >/dev/null 2>&1
        t2="$(nc_now_us)"

        start_ms="$(nc_us_to_ms "$(( t1 - t0 ))")"
        stop_ms="$(nc_us_to_ms "$(( t2 - t1 ))")"
        total_ms="$(nc_us_to_ms "$(( t2 - t0 ))")"
        stops+=("$stop_ms")
        totals+=("$total_ms")
        sum=$(( sum + stop_ms ))
        printf '%-6s %-12s %-12s %-12s\n' "$i" "$start_ms" "$stop_ms" "$total_ms"
    done

    printf '\n'
    nc_bench_stats "stop" "$NC_STOP_IPC_WAIT_MS" "${stops[@]}"
    nc_bench_stats "total" "" "${totals[@]}"
    return "$NC_EXIT_OK"
}

nc_bench_stats() {
    local label="$1" budget="$2"
    shift 2
    local -a v=("$@")
    local -i n="${#v[@]}" i j tmp
    for (( i = 1; i < n; i++ )); do
        tmp="${v[i]}"
        j=$(( i - 1 ))
        while [ "$j" -ge 0 ] && [ "${v[j]}" -gt "$tmp" ]; do
            v[$(( j + 1 ))]="${v[j]}"
            j=$(( j - 1 ))
        done
        v[$(( j + 1 ))]="$tmp"
    done
    local -i sum=0 min max avg p50 p95
    for i in "${v[@]}"; do sum=$(( sum + i )); done
    min="${v[0]}"
    max="${v[n - 1]}"
    avg=$(( sum / n ))
    p50="${v[$(( n / 2 ))]}"
    p95="${v[$(( (n * 95) / 100 >= n ? n - 1 : (n * 95) / 100 ))]}"
    printf '%-6s min=%sms  p50=%sms  p95=%sms  max=%sms  rata-rata=%sms' \
        "$label" "$min" "$p50" "$p95" "$max" "$avg"
    if [ -n "$budget" ]; then
        if [ "$p95" -le "$budget" ]; then
            printf '  [OK, di bawah anggaran %sms]' "$budget"
        else
            printf '  [LEBIH dari anggaran %sms]' "$budget"
        fi
    fi
    printf '\n'
}

nc_media_count_quick() {
    local -i n=0
    local f
    for f in "$NC_VIDEO_DIR"/*; do
        [ -f "$f" ] && n=$(( n + 1 ))
    done
    printf '%s' "$n"
}

# ---------------------------------------------------------------- check

# `doctor` menjawab "dependensi ada?". `check` menjawab "ini benar-benar
# akan jalan?", dengan menelusuri hal-hal yang tidak terlihat dari daftar
# dependensi: apakah tiap file benar-benar bisa didecode, apakah ambang idle
# masuk akal, apakah compositor mau menerima jendelanya.
nc_check_summary_fail=0
nc_check_summary_warn=0

nc_check_fail() {
    printf '  %sFAIL%s  %s\n' "$NC_TUI_C_RED" "$NC_TUI_C_RESET" "$*"
    nc_check_summary_fail=$(( nc_check_summary_fail + 1 ))
    return 0
}

nc_check_warn() {
    printf '  %sWARN%s  %s\n' "$NC_TUI_C_YELLOW" "$NC_TUI_C_RESET" "$*"
    nc_check_summary_warn=$(( nc_check_summary_warn + 1 ))
    return 0
}

nc_check_ok() {
    printf '  %sOK%s    %s\n' "$NC_TUI_C_GREEN" "$NC_TUI_C_RESET" "$*"
    return 0
}

nc_check_section() {
    printf '\n%s%s%s\n' "$NC_TUI_C_BOLD" "$*" "$NC_TUI_C_RESET"
}

nc_check_idle() {
    nc_check_section "Idle thresholds"
    if [ "$NC_IDLE_START_SEC" -lt 120 ] 2>/dev/null; then
        nc_check_warn "IDLE_START_SEC=${NC_IDLE_START_SEC}s terlalu pendek; layar akan berkedip saat membaca"
        nc_anomaly_emit "$NC_SEV_WARN" "IDLE_TOO_SHORT" \
            "IDLE_START_SEC=${NC_IDLE_START_SEC}s di bawah 120s" \
            "naikkan ke 600 atau lebih; layar berkedip setiap idle timeout"
    else
        nc_check_ok "screensaver menyala setelah ${NC_IDLE_START_SEC}s"
    fi
    if [ "$NC_IDLE_LOCK_SEC" -le "$NC_IDLE_START_SEC" ] 2>/dev/null; then
        nc_check_warn "IDLE_LOCK_SEC=${NC_IDLE_LOCK_SEC}s <= IDLE_START_SEC=${NC_IDLE_START_SEC}s; lockscreen akan muncul hampir bersamaan"
    else
        nc_check_ok "lockscreen setelah ${NC_IDLE_LOCK_SEC}s"
    fi
}

nc_check_outputs() {
    nc_check_section "Output monitor"
    if nc_detect_outputs; then
        local o
        for o in "${NC_OUTPUTS[@]}"; do
            nc_check_ok "$o aktif"
        done
        if [ "${#NC_OUTPUTS[@]}" -gt 1 ] && [ "$NC_MONITOR_MODE" != "all" ]; then
            nc_check_warn "${#NC_OUTPUTS[@]} output aktif tapi MONITOR_MODE=$NC_MONITOR_MODE; hanya satu yang akan tertutup"
        fi
        if [ "$NC_MONITOR_MODE" = "all" ]; then
            nc_check_warn "MONITOR_MODE=all bergantung compositor menaruh jendela;mpv tidak bisa memilih output di Wayland"
        fi
    else
        nc_check_warn "tidak bisa mendeteksi output monitor"
    fi
}

nc_check_hwdec() {
    nc_check_section "Akselerasi"
    if [ ! -d /dev/dri ]; then
        nc_check_warn "tidak ada /dev/dri; dekode akan jatuh ke software"
        return 0
    fi
    if ! nc_have mpv; then
        nc_check_fail "mpv tidak ditemukan"
        return 0
    fi

    # Decode nyata beberapa frame dari satu file representative, lalu tanya
    # mpv hwdec apa yang benar-benar terpakai. static config tidak bisa
    # memastikan ini - beberapa kombinasi driver diam-diam mundur ke software.
    local sample="" f
    for f in "$NC_VIDEO_DIR"/*; do
        [ -f "$f" ] || continue
        sample="$f"
        break
    done
    if [ -z "$sample" ]; then
        nc_check_warn "tidak ada file untuk menguji dekode"
        return 0
    fi

    local out
    out="$(timeout 30 mpv --no-config --no-terminal --really-quiet \
        --hwdec="$NC_HWDEC" --vo=null --ao=null \
        --frames=20 --no-audio "$sample" 2>&1)"
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        nc_check_fail "mpv gagal decode contoh dengan HWDEC=$NC_HWDEC"
        [ -n "$out" ] && printf '        %s\n' "$(printf '%s' "$out" | head -2)"
        return 0
    fi
    nc_check_ok "decode 20 frame dengan HWDEC=$NC_HWDEC"
    return 0
}

nc_check_media() {
    nc_check_section "Media"
    if [ ! -d "$NC_VIDEO_DIR" ]; then
        nc_check_fail "VIDEO_DIR tidak ada: $NC_VIDEO_DIR"
        return 0
    fi

    local -i total=0 bad=0 unreadable=0
    local f="" sz=0
    local -a broken=()
    for f in "$NC_VIDEO_DIR"/*; do
        [ -f "$f" ] || continue
        total=$(( total + 1 ))
        if [ ! -r "$f" ] || [ ! -s "$f" ]; then
            unreadable=$(( unreadable + 1 ))
            continue
        fi
        if nc_media_probe "$f"; then
            continue
        fi
        bad=$(( bad + 1 ))
        [ "${#broken[@]}" -lt 5 ] && broken+=("$(nc_anomaly_basename "$f")")
    done

    if [ "$total" -eq 0 ]; then
        nc_check_fail "tidak ada file video di $NC_VIDEO_DIR"
        nc_check_warn "isi dengan: $NC_APP aerials --sync"
        return 0
    fi

    if [ "$unreadable" -gt 0 ]; then
        nc_check_fail "$unreadable file kosong atau tidak bisa dibaca"
    fi
    if [ "$bad" -gt 0 ]; then
        nc_check_fail "$bad dari $total file gagal divalidasi (VALIDATE_MEDIA=$NC_VALIDATE_MEDIA)"
        for f in "${broken[@]}"; do
            printf '        - %s\n' "$f"
        done
        nc_check_warn "file-file itu akan dicoba lalu dilewati tiap start; hapus atau ganti"
    fi
    if [ "$unreadable" -eq 0 ] && [ "$bad" -eq 0 ]; then
        nc_check_ok "semua $total file lolos validasi"
    fi
    return 0
}

nc_check_socket() {
    nc_check_section "Runtime"
    if nc_is_running; then
        nc_check_ok "screensaver aktif (supervisor $(nc_supervisor_pid 2>/dev/null))"
    else
        nc_check_ok "tidak aktif"
    fi

    if [ -S "$NC_SOCK" ]; then
        local mode
        mode="$(stat -c '%a' "$NC_SOCK" 2>/dev/null)"
        case "$mode" in
            6?? | 7??) nc_check_ok "socket $NC_SOCK (mode=$mode)" ;;
            *)
                nc_check_fail "socket terlalu terbuka: mode=$mode"
                nc_anomaly_emit "$NC_SEV_WARN" "SOCKET_PERMISSIONS" \
                    "socket IPC mode=$mode, seharusnya 600/700" \
                    "periksa izin $XDG_RUNTIME_DIR" "mode=$mode"
                ;;
        esac
        if ! nc_ipc_property "$NC_SOCK" "idle-active" 0.5 >/dev/null 2>&1; then
            nc_check_warn "socket ada tapi tidak menjawab"
            nc_anomaly_emit "$NC_SEV_WARN" "IPC_UNREACHABLE" \
                "socket IPC tidak menjawab get_property" \
                "naikkan STARTUP_GRACE_MS, atau cek log" "sock=$NC_SOCK"
        fi
    else
        nc_check_ok "tidak ada socket (normal saat tidak aktif)"
    fi

    local health
    health="$(nc_anomaly_health)"
    if [ "$health" -ge 80 ] 2>/dev/null; then
        nc_check_ok "health $health/100"
    else
        nc_check_warn "health $health/100; lihat: $NC_APP anomalies --since all"
    fi
    return 0
}

nc_cmd_check() {
    nc_tui_setup_colors
    printf '%snoctoprevi check%s  %s\n\n' "$NC_TUI_C_BOLD" "$NC_TUI_C_RESET" \
        "preflight: apakah screensaver ini benar-benar akan jalan"
    nc_check_summary_fail=0
    nc_check_summary_warn=0

    nc_check_idle
    nc_check_outputs
    nc_check_hwdec
    nc_check_media
    nc_check_socket

    printf '\n--------------------------------------------------------------------------------\n'
    if [ "$nc_check_summary_fail" -gt 0 ]; then
        printf '%s%d problem%s, %s%d peringatan%s\n' \
            "$NC_TUI_C_RED" "$nc_check_summary_fail" "$NC_TUI_C_RESET" \
            "$NC_TUI_C_YELLOW" "$nc_check_summary_warn" "$NC_TUI_C_RESET"
        return "$NC_EXIT_ERROR"
    fi
    if [ "$nc_check_summary_warn" -gt 0 ]; then
        printf '%ssiap, dengan %s peringatan%s\n' \
            "$NC_TUI_C_YELLOW" "$nc_check_summary_warn" "$NC_TUI_C_RESET"
        return "$NC_EXIT_OK"
    fi
    printf '%sSemua bersih.%s\n' "$NC_TUI_C_GREEN" "$NC_TUI_C_RESET"
    return "$NC_EXIT_OK"
}

# --------------------------------------------------------------- selftest

# Pola uji untuk memastikan tiap monitor benar-benar tertutup. Penting untuk
# penyiapan multi-monitor: mpv tidak bisa memilih output di Wayland, jadi
# "tidak tahu apakah semua monitor ketutup" adalah kondisi yang sangat
# mungkin terjadi dan tidak terlihat kalau tidak diuji.
#
# Setiap output mendapat satu berkas .mp4 berbeda: SMPTE bars plus penanda
# bergerak, dan nama file-nya berisi nomor output. Setelah selesai, tinggal
# lihat layar: pola dan nomornya harus cocok dengan monitor yang kamu lihat.
# Klip pendek yang di-loop mpv (--loop-file=inf). Slaman 1 jam hanya
# memperlambat encoding tanpa menambah nilai uji.
nc_selftest_build() {
    local out="$1" secs="$2" w="${3:-1920}" h="${4:-1080}"
    ffmpeg -nostdin -loglevel error -y \
        -f lavfi -i "smptebars=size=${w}x${h}:rate=15:duration=$secs" \
        -f lavfi -i "testsrc2=size=320x180:rate=15:duration=$secs" \
        -filter_complex "[0:v][1:v]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" \
        -c:v libx264 -preset ultrafast -crf 32 -pix_fmt yuv420p \
        -t "$secs" "$out" 2>/dev/null
}

nc_cmd_selftest() {
    nc_tui_setup_colors

    local -i duration=30
    local -a targets=()
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --duration | -t)
                case "${2:-}" in
                    '' | *[!0-9]*) duration=30 ;;
                    *) duration="$2" ;;
                esac
                shift 2
                ;;
            *) shift ;;
        esac
    done

    nc_have ffmpeg || {
        nc_log_error "ffmpeg dibutuhkan untuk membuat pola uji"
        printf '  %sFAIL%s  ffmpeg tidak ditemukan\n' "$NC_TUI_C_RED" "$NC_TUI_C_RESET"
        return "$NC_EXIT_ERROR"
    }

    local workdir="${nc_selftest_dir_default:-$NC_STATE_DIR/selftest}"
    mkdir -p "$workdir" 2>/dev/null || {
        nc_log_error "gagal membuat $workdir"
        return "$NC_EXIT_ERROR"
    }

    printf '%snoctoprevi selftest%s\n\n' "$NC_TUI_C_BOLD" "$NC_TUI_C_RESET"
    printf 'Pola uji untuk memastikan tiap monitor tertutup. Setiap output\n'
    printf 'diberi satu berkas dengan nomor berbeda, jadi mudah dicocokkan.\n\n'

    local -a outputs=()
    if nc_detect_outputs; then
        outputs=("${NC_OUTPUTS[@]}")
    fi
    if [ "${#outputs[@]}" -eq 0 ]; then
        printf '  %sWARN%s  tidak ada output terdeteksi; memakai 2 output virtual\n' \
            "$NC_TUI_C_YELLOW" "$NC_TUI_C_RESET"
        outputs=(output-0 output-1)
    fi

    local o="" i="" idx=""
    for (( i = 0; i < ${#outputs[@]}; i++ )); do
        o="${outputs[i]}"
        idx="$i"
        local file=""
        file="$workdir/$(printf 'selftest-%02d' "$idx").mp4"
        printf '  %s[1]%s %-16s -> %s\n' "$NC_TUI_C_CYAN" "$NC_TUI_C_RESET" "$o" \
            "$(nc_tui_short_path "$file")"
        if nc_selftest_build "$file" "$duration"; then
            printf '      %sselesai%s\n' "$NC_TUI_C_GREEN" "$NC_TUI_C_RESET"
        else
            printf '      %sgagal membuat pola%s\n' "$NC_TUI_C_RED" "$NC_TUI_C_RESET"
            return "$NC_EXIT_ERROR"
        fi
        targets+=("$file")
    done

    printf '\n'
    printf 'Menjalankan screensaver. Perhatikan setiap monitor:\n'
    printf '  - nomor di tengah layar HARUS cocok dengan urutan output di atas\n'
    printf '  - tidak boleh ada monitor yang tetap menampilkan WALLPAPER\n'
    printf '  - kotak bergerak di tengah = video hidup, kalau beku decode-nya macet\n\n'
    printf 'Mulai sekarang? [y/N] '
    local go=""
    read -r go || true
    case "$(printf '%s' "$go" | tr 'A-Z' 'a-z')" in
        y | yes) ;;
        *)
            printf 'Dibatalkan. Berkas pola ada di: %s\n' "$workdir"
            printf 'Untuk dipakai manual, taruh salah satunya di VIDEO_DIR lalu:\n'
            printf '  %s start\n\n' "$NC_APP"
            return "$NC_EXIT_OK"
            ;;
    esac

    local bak=""
    bak="$NC_STATE_DIR/selftest-config.$$"
    if [ -f "$NC_CONFIG_FILE" ]; then
        cp -f "$NC_CONFIG_FILE" "$bak" 2>/dev/null
    fi
    # Config ditimpa hanya selama selftest berjalan. Kalau proses ini
    # terputus di tengah - timeout, Ctrl-C, terminal ditutup - config asli
    # harus tetap dikembalikan. Tanpa trap, configmu akan selamanya
    # menunjuk folder pola uji.
    nc_selftest_restore() {
        [ -n "$bak" ] || return 0
        [ -f "$bak" ] || return 0
        mv -f "$bak" "$NC_CONFIG_FILE" 2>/dev/null
        printf '\nConfig dipulihkan.\n'
    }
    trap 'nc_selftest_restore' INT TERM HUP
    trap 'nc_selftest_restore; exit 130' INT
    trap 'nc_selftest_restore; exit 143' TERM

    printf 'VIDEO_DIR=%s\nPLAYBACK_MODE=sequential\nVALIDATE_MEDIA=0\nLOG_LEVEL=error\n' \
        "$workdir" >"$NC_CONFIG_FILE" 2>/dev/null

    nc_cmd_start
    sleep 2
    printf 'Ctrl-C untuk berhenti, atau Enter setelah selesai.\n'
    read -r _ || true
    nc_cmd_stop

    trap - INT TERM HUP
    nc_selftest_restore
    printf 'Pola uji tetap ada di: %s\n' "$workdir"
    printf 'Hapus dengan: rm -rf %s\n\n' "$workdir"
    return "$NC_EXIT_OK"
}
